### ISSUE TITLE
Two-way sync to mirror tracking services progress in app

### ISSUE THREAD

**Issue by pjueon** [Quickdesh/Animiru#67]
### Describe your suggested feature

Currently, the tracking sync feature operates in a one-way direction: from Animiru to the tracking services. By implementing a two-way sync (between Animiru and the tracking services), users can effortlessly synchronize their watch progress across multiple devices. An existing Tachiyomi fork already incorporates this functionality, which can be found at this link: https://github.com/Saud-97/TachiyomiS97.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Implemented in d2f1d920266a3da1a7eea6b6724e9f561244868d
