### ISSUE TITLE
Anilist tracking not working automatically

### ISSUE THREAD

**Issue by Manuukapor** [Quickdesh/Animiru#75]
### Steps to reproduce

I have linked my anilist account but I can't see any anime i have tracked in the past. And i have to track each n every anime manually and mark the episodes i have seen manually too

### Expected behavior

I expect that when i add an anime in my library and track it too, it should automatically show me that i have already watched it in the past(which i already have) and if i haven't watched it then i might have watched some of it so, it should tracked automatically. 

### Actual behavior

![Screenshot_2023-12-20-02-45-54-801_xyz Quickdev Animiru mi](https://github.com/Quickdesh/Animiru/assets/129563032/6eaae298-a699-42cf-bc06-b890fd338724)
![Screenshot_2023-12-20-02-45-50-061_xyz Quickdev Animiru mi](https://github.com/Quickdesh/Animiru/assets/129563032/1c48d25f-b24e-47e5-a012-41e7a7cdeab9)
When i link my anilist account it should show me those anime (in the home page) that i have watched in the past but it didn't 

### Animiru version

0.16.0.0

### Android version

Android version 12

### Device

Redmi note 10s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lasersPew** [comment]
> I have linked my anilist account but I can't see any anime i have tracked in the past. 

If you want to import things from anilist onto your library, then no, Animiru or anything related to Aniyomi or ~Tachi~Mihon cannot do that.

> it should automatically show me that i have already watched it in the past

It would, if you added it to your account (like using MALSync)

> if i haven't watched it then i might have watched some of it so, it should tracked automatically.

There are a setting to automatically track things as soon as you finish an episode if you added trackers in it. Also, aniyomi can give you the date when you started watching that anime ~afaik~ when you click the start/end date.
